### ISSUE TITLE
Missing TLS support

### ISSUE THREAD

**Issue by MCRrAMKkE4** [tapglue/snaas#37]
In the [overview docs page](https://github.com/tapglue/snaas/wiki/overview#ssl-only) it is mentioned:

> SSL Only
> 
> We require that all requests are done over SSL, thus all access is over HTTPS, and accessed from the api.tapglue.com domain. Unencrypted HTTP is not supported.

and in the [cmd/gateway-http/gateway-http.go file line 885](https://github.com/tapglue/snaas/blob/master/cmd/gateway-http/gateway-http.go#L883) I see a comment saying `	// TODO: Handle TLS.`

In the press release after the acquisition by Localytics:
- https://www.localytics.com/press/press_release/localytics-acquires-tapglue-to-help-enterprises-improve-mobile-engagement/
- https://medium.com/tapglue-stories/tapglue-got-acquired-by-boston-based-localytics-820c6fcde7c2

says:

> The Tapglue platform will survive, although in a different form. We decided to not continue our managed service, but focus on the core Localytics product initiatives. However, **we made our powerful platform _completely_ available as an open source project** — probably the most comprehensive open-source project for building social features for apps. Check out Github to learn more about it.

> The Tapglue platform is now completely open source and available for free to the mobile developer community. 

Does this mismatch mean that the code in this GitHub repository is not the same as the one used in production at https://api.tapglue.com ?

**Comment by xla** [comment]
> Does this mismatch mean that the code in this GitHub repository is not the same as the one used in production at https://api.tapglue.com ?

The open-source version was cleansed and cleaned, but otherwise is the codebase that powered the Tapglue product.

While it is desired to have end-to-end encryption the boundary where we are most keen on having it is on the perimeter which is reflected in our [infrastructure](https://github.com/tapglue/snaas/blob/master/infrastructure/terraform/template/platform.tf#L236-L242). Given that in a production scenario all requests are SSL terminated at least until they reach internal network. Certainly something that can be added to have end-to-end encryption, but would require that all intermediates along the way speak layer4 exclusively.
