### ISSUE TITLE
Can you guys add a one click deploy to Heroku ?

### ISSUE THREAD

**Issue by batiron** [tapglue/snaas#42]
Hey guys can you guys add a 1 Click deploy to something like Heroku or Docker file that will allow us to get up and  running quickly

**Comment by xla** [comment]
Hej @batiron, thanks for reaching out. It would be good to address in a non-gender specific way in our public repositories.

When it comes to 1-click deploys I'd like to challenge the feasibility of it as this is a non-trivial project that has a lot of moving parts in order to be fully functional. Yet everything should be there for you to have it running as the infrastructure directory not only holds Dockerfiles for all bits, but also has complete Terraform descriptions to either run it yourself or get an overview what it requires to run. Reopen if you see possibilities to make a 1-click deploy possible, or have any other questions.
